# src/coordinator/services/persona_lines.py
"""Lines the system needs to say, said in the persona's own voice.

A companion that speaks in character for forty turns and then emits
"Here, I made this for you." has broken character at the one moment the user
is paying attention — the moment something actually happened. These are
status messages wearing a conversation's clothes, and the user hears the
difference.

So every user-facing line the IMAGE path needs is generated by the persona
rather than written here. The strings in `_FALLBACK` are not the product;
they are what is said when the model cannot be reached, and nothing else.

Three properties this has to have, each from a constraint rather than taste:

1. **Cached, and several variants.** Generating on every notification would
   add an LLM call to a path whose whole purpose is to be out of band, and
   one cached line would make her say the same sentence every single time —
   which reads as canned even when it is in voice. Three variants per
   situation, chosen at random, is enough that it does not feel scripted.

2. **Warmable.** ⚠️ The BUSY line is the hard case: it is said precisely when
   the arbiter has unloaded the companion model, so it cannot be generated at
   the moment it is needed. `warm()` exists for that — the worker calls it
   BEFORE evicting, while the model is still resident. Without that ordering
   the busy line is the one line guaranteed to fall back to a canned string.

3. **Never raises, never blocks.** Every caller is on a path where a failure
   would be worse than a generic sentence: a notification that cannot be
   phrased must still be delivered.
"""

from __future__ import annotations

import logging
import random
import re
import threading

logger = logging.getLogger(__name__)

#: How many variants to generate per situation. Three is the smallest number
#: that stops a repeat feeling scripted across a handful of images in a
#: session; more would cost LLM time for diminishing returns.
_VARIANTS = 3

#: What to ask for. Describes the SITUATION only — never the wording — so the
#: persona supplies the voice and this file supplies none of it.
SITUATIONS: dict[str, str] = {
    "image_ready": (
        "You made a picture for the person you are talking to, and you are "
        "handing it to them now. You have NOT seen it and do not know what is "
        "in it."
    ),
    "image_failed": (
        "You tried to make a picture for the person you are talking to and it "
        "did not work. You are telling them so. You do not know the technical "
        "reason."
    ),
    "image_cancelled": (
        "You stopped making a picture for the person you are talking to "
        "before it finished, and you are telling them it is not coming."
    ),
    "image_busy": (
        "You are part-way through making a picture for the person you are "
        "talking to. It needs a few more minutes and you cannot talk properly "
        "until it is done. You are asking them to wait."
    ),
    "image_not_started": (
        "The person you are talking to asked you for a picture and you could "
        "not get it started. You are asking them to try again. This is a "
        "technical hiccup, NOT a refusal — you are willing."
    ),
    "image_missing": (
        "You made a picture for the person you are talking to but can no "
        "longer find it, so you cannot send it."
    ),
}

#: Appended to every situation. Two failures it prevents, both observed on
#: the first live generation of these lines:
#:
#:   - gwen described the picture's CONTENT ("look at me holding that pose")
#:     for an image of a snowy forest. The line is written before anyone has
#:     seen the file, so describing it is fabrication — the same failure the
#:     whole generation path is built to avoid, relocated into the caption.
#:   - eeva answered as though discussing someone else's work ("Do you think
#:     it's complete?") and her refusal line tripped the known LEAN_SAFETY
#:     leak ("I cannot and will not..."), which is a safety opener and not a
#:     technical apology.
_GUARD = (
    "\n\nDo NOT describe what is in the picture — you have not seen it. "
    "Do not refuse, moralise, or open with 'I cannot'. Speak directly to "
    "them about the picture you are making for them."
)

#: Said ONLY when the model cannot be reached. Not the product.
_FALLBACK: dict[str, str] = {
    "image_ready": "Here — I made this for you.",
    "image_failed": "I tried to make that picture and it didn't work out.",
    "image_cancelled": "I stopped making that picture.",
    "image_busy": (
        "I'm still drawing — it takes me a few minutes and I can't talk while "
        "I do it. I'll send it over as soon as it's done."
    ),
    "image_not_started": (
        "I couldn't get that started just now — ask me again and I'll try "
        "once more."
    ),
    "image_missing": "I made that picture but I can't find it any more.",
}

_cache: dict[tuple[str, str], list[str]] = {}
_lock = threading.Lock()

#: A reply is one line to a person, not a paragraph and not a stage direction.
_MAX_CHARS = 220


def _clean(text: str) -> str:
    """One plain line. Models wrap these in quotes and narration unprompted."""
    text = (text or "").strip()
    text = re.sub(r"^```[a-z]*\s*|\s*```$", "", text).strip()
    # Take the first non-empty line: the model often offers alternatives.
    for candidate in text.splitlines():
        candidate = candidate.strip()
        if not candidate:
            continue
        candidate = re.sub(r"^\s*[-*\d.)\s]+", "", candidate).strip()
        candidate = candidate.strip('"').strip("'").strip()
        # Drop a leading "Gwen:" style speaker tag.
        candidate = re.sub(r"^[A-Z][\w .]{0,20}:\s*", "", candidate)
        if candidate:
            return candidate[:_MAX_CHARS].strip()
    return ""


def _generate(persona_key: str, situation: str) -> list[str]:
    """Ask the persona for `_VARIANTS` ways to say it. [] on any failure."""
    from ..llm_client import create_llm_client
    from ..persona_memory import build_system_prompt, get_persona_card

    description = SITUATIONS.get(situation)
    if description is None:
        return []

    card = get_persona_card(persona_key)
    if not card:
        return []

    instruction = (
        f"{description}{_GUARD}\n\n"
        f"Write {_VARIANTS} different short things you might say, one per "
        f"line, in your own voice. One sentence each. No numbering, no "
        f"quotes, no narration or stage directions, no asterisks. Just the "
        f"lines themselves."
    )
    try:
        client = create_llm_client(card)
        raw = client.complete(
            system=build_system_prompt(persona_key, include_examples=True),
            user_prompt=instruction,
        )
    except Exception as exc:  # noqa: BLE001 — a phrasing helper never raises
        logger.info("[Lines] %s/%s not generated: %s", persona_key, situation, exc)
        return []

    out = []
    for raw_line in (raw or "").splitlines():
        cleaned = _clean(raw_line)
        if cleaned and cleaned not in out:
            out.append(cleaned)
    return out[:_VARIANTS]


def line(persona_key: str, situation: str) -> str:
    """One in-voice line for `situation`. Falls back rather than failing.

    Cached per (persona, situation) for the process lifetime — these describe
    recurring situations, not this particular image, so there is nothing to
    invalidate.
    """
    key = (persona_key, situation)
    with _lock:
        cached = _cache.get(key)
    if cached:
        return random.choice(cached)

    generated = _generate(persona_key, situation)
    if generated:
        with _lock:
            _cache[key] = generated
        logger.info("[Lines] cached %d variant(s) for %s/%s",
                    len(generated), persona_key, situation)
        return random.choice(generated)

    return _FALLBACK.get(situation, "")


def warm(persona_key: str, situations: tuple[str, ...] = ("image_busy",)) -> None:
    """Fill the cache while the model is REACHABLE.

    ⚠️ Called by the image worker immediately BEFORE it evicts the companion
    model. `image_busy` is said exactly when that model is gone, so this is
    the only moment it can be generated at all — reverse the order and the
    one line a user sees most during a generation is the one guaranteed to be
    canned.
    """
    for situation in situations:
        with _lock:
            if _cache.get((persona_key, situation)):
                continue
        generated = _generate(persona_key, situation)
        if generated:
            with _lock:
                _cache[(persona_key, situation)] = generated
            logger.info("[Lines] warmed %s/%s (%d variants)",
                        persona_key, situation, len(generated))
        else:
            logger.info("[Lines] could not warm %s/%s — the fallback will be "
                        "used if it is needed", persona_key, situation)


def reset_cache() -> None:
    """Drop every cached line. For tests, and for a persona-card edit."""
    with _lock:
        _cache.clear()
