# tests/backend/coordinator/test_media_storage.py
"""Unit tests for the media filesystem layer (Telegram image transport, phase 1).

Hermetic: MEDIA_ROOT points at tmp_path, flags toggled via env + settings cache
clear. Nothing here touches the real media root.

The path-guard tests are the load-bearing ones. POST /sessions/import accepts a
client-supplied session id, so a directory name reaching this module may be
attacker-shaped — and the two guards catch different things, which is why both
are asserted separately.
"""

from __future__ import annotations

import hashlib
import os
import stat

import pytest

from src.coordinator.config import get_settings
from src.coordinator.services import media_storage
from src.coordinator.services.media_fixture import build_probe_png
from src.coordinator.services.media_storage import MediaStorageError

#: Pinned so a regression in the encoder fails immediately rather than being
#: silently re-committed. Generated bytes are deterministic; a blob would not be
#: self-checking.
PROBE_SHA256 = "281d1cfc6b52c29b56efa8d1595d089c5310cc3b67fec17d8315d2037953f4a0"

DIR_A = "a" * 32
DIR_B = "b" * 32


# ---------- Fixtures ----------


@pytest.fixture(autouse=True)
def _clean_settings_cache():
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


@pytest.fixture
def media_on(tmp_path, monkeypatch):
    """Media enabled, rooted at a throwaway directory."""
    root = tmp_path / "media"
    monkeypatch.setenv("MEDIA_ENABLED", "true")
    monkeypatch.setenv("MEDIA_ROOT", str(root))
    get_settings.cache_clear()
    return root


# ---------- Tests — the probe fixture ----------


def test_probe_png_is_a_png_of_the_expected_size():
    png = build_probe_png(256)
    assert png.startswith(b"\x89PNG\r\n\x1a\n")
    assert media_storage.png_dimensions(png) == (256, 256)


def test_probe_png_is_deterministic():
    assert hashlib.sha256(build_probe_png()).hexdigest() == PROBE_SHA256


def test_probe_png_rejects_absurd_sizes():
    with pytest.raises(ValueError):
        build_probe_png(0)
    with pytest.raises(ValueError):
        build_probe_png(99999)


# ---------- Tests — png_dimensions never raises ----------


@pytest.mark.parametrize(
    "payload",
    [b"", b"not a png", b"\x89PNG\r\n\x1a\n", b"\x89PNG\r\n\x1a\n" + b"\x00" * 16],
)
def test_png_dimensions_returns_none_rather_than_raising(payload):
    """A metadata helper that throws turns a cosmetic gap into a failed request."""
    assert media_storage.png_dimensions(payload) is None


# ---------- Tests — session_dir path guards ----------


@pytest.mark.parametrize(
    "bad",
    [
        "../../etc",
        "..",
        "",
        "a" * 31,
        "a" * 33,
        "A" * 32,  # uppercase: APFS is case-insensitive, so this could collide
        "g" * 32,  # not hex
        "a" * 31 + "/",
        "sessions/../../etc",
    ],
)
def test_session_dir_rejects_non_hex_names(media_on, bad):
    with pytest.raises(MediaStorageError):
        media_storage.session_dir(bad)


def test_session_dir_rejects_non_string(media_on):
    with pytest.raises(MediaStorageError):
        media_storage.session_dir(None)  # type: ignore[arg-type]


def test_session_dir_accepts_a_legal_name(media_on):
    resolved = media_storage.session_dir(DIR_A)
    assert resolved.is_relative_to(media_on.resolve())
    assert resolved.name == DIR_A


def test_session_dir_rejects_a_symlink_escaping_the_root(media_on, tmp_path):
    """The guard the regex alone cannot provide: a legal-looking name whose
    directory is a symlink pointing outside the media root."""
    outside = tmp_path / "outside"
    outside.mkdir()
    sessions = media_on / "sessions"
    sessions.mkdir(parents=True)
    os.symlink(outside, sessions / DIR_A)

    with pytest.raises(MediaStorageError, match="escapes"):
        media_storage.session_dir(DIR_A)


def test_session_dir_rejects_a_trailing_newline(media_on):
    """Regression: `^...$` with .match() accepts a trailing newline, so
    "a"*32 + "\\n" resolved successfully and put a newline into a filename that
    travels to the gateway and into logs. fullmatch closes it."""
    with pytest.raises(MediaStorageError):
        media_storage.session_dir(DIR_A + "\n")


def test_session_dir_checks_containment_AFTER_appending_subdirs(media_on, tmp_path):
    """Regression, and the reason `parts` exists.

    An earlier revision containment-checked the session directory and let the
    caller append `/ "img"` afterwards, so a symlink one level deeper escaped
    the root — at exactly the path that gets written. Demonstrated escape
    before the fix; this pins the closure.
    """
    outside = tmp_path / "outside"
    outside.mkdir()
    sess = media_on / "sessions" / DIR_A
    sess.mkdir(parents=True)
    os.symlink(outside, sess / "img")

    with pytest.raises(MediaStorageError, match="escapes"):
        media_storage.session_dir(DIR_A, "img")


@pytest.mark.parametrize("part", ["..", "../etc", "IMG", "a/b", "", "x" * 33])
def test_session_dir_rejects_bad_subdir_names(media_on, part):
    with pytest.raises(MediaStorageError):
        media_storage.session_dir(DIR_A, part)


# ---------- Tests — atomic_write ----------


def test_atomic_write_round_trips(tmp_path):
    target = tmp_path / "nested" / "out.bin"
    payload = b"\x00\x01\x02" * 1000
    media_storage.atomic_write(target, payload)
    assert target.read_bytes() == payload


def test_atomic_write_leaves_mode_644(tmp_path):
    """mkstemp creates 0600 and os.replace preserves the source mode, so without
    an explicit chmod the published file is unreadable by anything else."""
    target = tmp_path / "out.bin"
    media_storage.atomic_write(target, b"x")
    assert stat.S_IMODE(target.stat().st_mode) == 0o644


def test_atomic_write_leaves_no_temp_residue(tmp_path):
    target = tmp_path / "out.bin"
    media_storage.atomic_write(target, b"x" * 100)
    assert [p.name for p in tmp_path.iterdir()] == ["out.bin"]


def test_atomic_write_replaces_an_existing_file_wholly(tmp_path):
    target = tmp_path / "out.bin"
    media_storage.atomic_write(target, b"old")
    big = b"n" * 5_000_000
    media_storage.atomic_write(target, big)
    assert target.stat().st_size == len(big)
    assert target.read_bytes() == big


def test_atomic_write_cleans_up_when_the_write_fails(tmp_path, monkeypatch):
    target = tmp_path / "out.bin"

    def _boom(*_a, **_k):
        raise OSError("disk full")

    monkeypatch.setattr(media_storage.os, "fsync", _boom)
    with pytest.raises(OSError):
        media_storage.atomic_write(target, b"x")

    assert not target.exists()
    assert list(tmp_path.iterdir()) == []


# ---------- Tests — store_png ----------


def test_store_png_refuses_when_disabled(tmp_path, monkeypatch):
    monkeypatch.setenv("MEDIA_ENABLED", "false")
    monkeypatch.setenv("MEDIA_ROOT", str(tmp_path))
    get_settings.cache_clear()
    with pytest.raises(MediaStorageError, match="disabled"):
        media_storage.store_png(DIR_A, build_probe_png())


def test_store_png_writes_and_describes_the_file(media_on):
    png = build_probe_png()
    stored = media_storage.store_png(DIR_A, png)

    assert stored.path.exists()
    assert stored.path.read_bytes() == png
    assert stored.bytes == len(png)
    assert stored.sha256 == hashlib.sha256(png).hexdigest()
    assert (stored.width, stored.height) == (256, 256)
    assert stored.path.is_relative_to(media_on.resolve())


def test_store_png_never_reuses_a_media_id(media_on):
    png = build_probe_png(16)
    first = media_storage.store_png(DIR_A, png)
    second = media_storage.store_png(DIR_A, png)
    assert first.media_id != second.media_id
    assert first.path.parent == second.path.parent


def test_store_png_separates_sessions(media_on):
    png = build_probe_png(16)
    a = media_storage.store_png(DIR_A, png)
    b = media_storage.store_png(DIR_B, png)
    assert a.path.parent != b.path.parent


@pytest.mark.parametrize(
    "payload,match",
    [
        (b"", "empty"),
        (b"GIF89a-not-a-png", "not a PNG"),
    ],
)
def test_store_png_rejects_bad_payloads(media_on, payload, match):
    with pytest.raises(MediaStorageError, match=match):
        media_storage.store_png(DIR_A, payload)


def test_store_png_enforces_the_size_cap(tmp_path, monkeypatch):
    monkeypatch.setenv("MEDIA_ENABLED", "true")
    monkeypatch.setenv("MEDIA_ROOT", str(tmp_path))
    monkeypatch.setenv("MEDIA_MAX_BYTES", "1000")
    get_settings.cache_clear()
    with pytest.raises(MediaStorageError, match="over the"):
        media_storage.store_png(DIR_A, build_probe_png())


def test_store_png_propagates_the_path_guard(media_on):
    """store_png must not be a way around session_dir."""
    with pytest.raises(MediaStorageError):
        media_storage.store_png("../../etc", build_probe_png())


def test_store_png_refuses_a_symlinked_img_dir(media_on, tmp_path):
    """The end-to-end form of the containment regression: the escape was
    reachable through store_png, which is the only caller that matters."""
    outside = tmp_path / "outside"
    outside.mkdir()
    sess = media_on / "sessions" / DIR_A
    sess.mkdir(parents=True)
    os.symlink(outside, sess / "img")

    with pytest.raises(MediaStorageError, match="escapes"):
        media_storage.store_png(DIR_A, build_probe_png(16))
    assert list(outside.iterdir()) == []


def test_store_png_stages_outside_img(media_on):
    """Debris from a crashed write must not land in img/, which callers
    enumerate as 'this session's media' and the phase-3 sweeper scans."""
    media_storage.store_png(DIR_A, build_probe_png(16))
    img = media_storage.session_dir(DIR_A, "img")
    assert [p.suffix for p in img.iterdir()] == [".png"]
    assert media_storage.session_dir(DIR_A, "tmp").is_dir()


# ---------- Tests — quarantine (phase 3) ----------


def test_quarantine_moves_the_tree_out_of_the_live_root(media_on):
    media_storage.store_png(DIR_A, build_probe_png(16))
    media_storage.store_png(DIR_A, build_probe_png(16))
    live = media_storage.session_dir(DIR_A)
    assert live.exists()

    count = media_storage.quarantine_session(DIR_A)

    assert count == 2
    assert not live.exists()
    quarantined = list((media_on.resolve() / "orphans").iterdir())
    assert len(quarantined) == 1
    assert DIR_A in quarantined[0].name
    # Quarantine, not deletion: the bytes are still there for 30 days.
    assert len(list(quarantined[0].rglob("*.png"))) == 2


def test_quarantine_is_zero_when_there_was_nothing(media_on):
    """The common case, and not an error."""
    assert media_storage.quarantine_session(DIR_A) == 0


def test_quarantine_twice_does_not_clobber_the_first(media_on):
    """Two resets in the same second must not have the second overwrite the
    first's quarantine — that would destroy exactly what quarantine exists to
    preserve."""
    media_storage.store_png(DIR_A, build_probe_png(16))
    media_storage.quarantine_session(DIR_A)
    media_storage.store_png(DIR_A, build_probe_png(16))
    media_storage.quarantine_session(DIR_A)

    entries = list((media_on.resolve() / "orphans").iterdir())
    assert len(entries) == 2
    assert sum(len(list(e.rglob("*.png"))) for e in entries) == 2


def test_quarantine_rejects_a_bad_media_dir(media_on):
    with pytest.raises(MediaStorageError):
        media_storage.quarantine_session("../../etc")


def test_a_new_image_after_quarantine_starts_clean(media_on):
    media_storage.store_png(DIR_A, build_probe_png(16))
    media_storage.quarantine_session(DIR_A)
    fresh = media_storage.store_png(DIR_A, build_probe_png(16))
    assert fresh.path.exists()
    assert len(list(media_storage.session_dir(DIR_A, "img").iterdir())) == 1
